DECLARE
CURSOR A IS SELECT SALARY,FIRST_NAME,DEPARTMENT_ID,JOB_ID FROM EMPLOYEES FOR UPDATE OF SALARY;
 V_DATA A%ROWTYPE;
 BEGIN
FOR V_DATA IN A
 LOOP
 IF V_DATA.JOB_ID='SH_CLERK' and V_DATA.DEPARTMENT_ID='10'
THEN
 UPDATE EMPLOYEES SET SALARY=(SALARY+SALARY*0.2) WHERE CURRENT OF A;
 DBMS_OUTPUT.PUT_LINE(V_DATA.SALARY || ''||V_DATA.FIRST_NAME);
  ELSIF V_DATA.JOB_ID='ST_MAN' and V_DATA.DEPARTMENT_ID='20'
THEN
UPDATE EMPLOYEES SET SALARY=(SALARY+SALARY*0.05) WHERE CURRENT OF A;
DBMS_OUTPUT.PUT_LINE(V_DATA.SALARY || ''||V_DATA.FIRST_NAME);
else
UPDATE EMPLOYEES SET SALARY=(SALARY+SALARY*0.1) WHERE CURRENT OF A;
DBMS_OUTPUT.PUT_LINE(V_DATA.SALARY || ''||V_DATA.FIRST_NAME);
end if;
END LOOP;