CREATE OR REPLACE FUNCTION USER_ANNUAL_COMP
  (
  p_eno EMP.EMPNO%TYPE,
  p_sal EMP.SAL%TYPE,
  p_comm EMP.COMM%TYPE
  ) RETURN NUMBER
  IS
 V_ANN NUMBER;
 V_EID NUMBER;
 V_SAL NUMBER;
 V_COMM NUMBER;
  BEGIN
  SELECT EMPNO,NVL(SAL,0),NVL(COMM,0) INTO V_EID,V_SAL,V_COMM FROM EMP WHERE
EMPNO=p_eno;
 V_ANN:=(p_sal+p_comm)*12;
  RETURN V_ANN;
  EXCEPTION
  WHEN NO_DATA_FOUND THEN
  DBMS_OUTPUT.PUT_LINE('ERROR..');
  END;