DECLARE
	BID        BOOKING.BOOK_ID%TYPE;
	BDATE  BOOKING.BOOKING_DATE%TYPE;
	PB          BOOKING.PERSON_BOOKED%TYPE;
	TID         BOOKING.THEARTRE_ID%TYPE;
	MID        BOOKING. MOVIE_ID%TYPE;
	SID         BOOKING.SHOW_ID%TYPE;
	NT          BOOKING.NO_OF_TICKETS%TYPE;
	MBID BOOKING.BOOK_ID%TYPE;
	SHID  BOOKING.SHOW_ID%TYPE;
	B1 EXCEPTION;
	B2 EXCEPTION;
	B3 EXCEPTION;
	B4 EXCEPTION;
	B5 EXCEPTION;
	B6 EXCEPTION;
	B7 EXCEPTION;
BEGIN
	BID :='&BOOKINGID';
	BDATE :='&BOOKDATE';
	PB :='&PERSONBOOKED';
	TID:='&THEATREID';
	MID:='&MOVIEID';
	SID:='&SHOWID';
	NT:='&NOOFTICKS';
	SELECT MAX(BOOK_ID) INTO MBID FROM       BOOKING;
	IF BID!=NVL(MBID,0)+1 THEN
	  RAISE B1;
	END IF;
	IF BDATE=SYSDATE THEN
	RAISE B2; 
	END IF;
	IF PB='PB' THEN
	RAISE B3;
	END IF;
	IF TID NOT LIKE 'TRT%' THEN
	RAISE B4;
	END IF;
	IF MID NOT LIKE 'MOV%' THEN
	RAISE B5;
	END IF;
	SELECT MAX(SHOW_ID) INTO SHID FROM BOOKING;
	IF SHID!=NVL(SHID,0)+1 THEN
	RAISE B6;
	END IF;
	IF NT=2 THEN
	RAISE B7;
	END IF;
	INSERT INTO BOOKING VALUES(BID,BDATE,PB,TID,MID,SID,NT);
	DBMS_OUTPUT.PUT_LINE('1 RECORD INSERTED');
	

EXCEPTION
	WHEN B1 THEN
	DBMS_OUTPUT.PUT_LINE('BOOKING ID IS NOT VALID ');	
	
	WHEN B2 THEN
	DBMS_OUTPUT.PUT_LINE('BOOKING DATE IS SYSDATE');

	WHEN B3 THEN
	DBMS_OUTPUT.PUT_LINE('PERSON BOOKED IS USER ITSELF!!');

	WHEN B4 THEN
	 DBMS_OUTPUT.PUT_LINE('THEATRE ID IS NOT VALID');

	WHEN B5 THEN
	 DBMS_OUTPUT.PUT_LINE('MOVIE ID IS NOT VALID');

	WHEN B6 THEN
	 DBMS_OUTPUT.PUT_LINE('SHOW ID IS NOT VALID');

	WHEN B7 THEN
	DBMS_OUTPUT.PUT_LINE('NO OF TICKETS ARE 2');


END;
/