CREATE OR REPLACE PROCEDURE ADD_EMPLOYEE
(
	P_EID      EMPLOYEES.EMPLOYEE_ID%TYPE,
	P_JOB       EMPLOYEES.JOB_ID%TYPE,
  	P_MGR     EMPLOYEES.MANAGER_ID%TYPE,
	P_HDATE  EMPLOYEES.HIRE_DATE%TYPE,
	P_SAL        EMPLOYEES.SALARY%TYPE,
	P_COMM EMPLOYEES.COMMISSION_PCT%TYPE,
	P_DID       EMPLOYEES.department_id%TYPE
)
IS
	
	CURSOR E IS SELECT * FROM EMPLOYEES;
	

BEGIN
	
	FOR V_E IN E
	LOOP
	IF(P_JOB='PROGRAMMER' OR (P_JOB='ACCOUNTANT' AND P_COMM IS NOT NULL)  OR P_JOB='PUBLIC ACCOUNTANT') THEN
	IF (P_MGR=V_E.EMPLOYEE_ID) THEN
	IF (P_HDATE<SYSDATE) THEN
	IF(P_SAL >800) THEN
	IF (P_DID=V_E.DEPARTMENT_ID) THEN
	INSERT INTO EMPLOYEES(EMPLOYEE_ID,JOB_ID,MANAGER_ID,HIRE_DATE,SALARY,COMMISSION_PCT,DEPARTMENT_ID)
	VALUES(P_EID,P_JOB,P_MGR ,P_HDATE,P_SAL ,P_COMM,P_DID);
	END IF;
	ELSE
	DBMS_OUTPUT.PUT_LINE('DEPT ENTERED IS NOT PRESENT IN TABLE');
	END IF;
	ELSE
	DBMS_OUTPUT.PUT_LINE('SALARY MUST BE GREATER THAN 800');
	END IF;
	ELSE
	DBMS_OUTPUT.PUT_LINE('HIREDATE MUST BE LESS THAN SYSDATE');
	END IF;
	ELSE
	DBMS_OUTPUT.PUT_LINE('MGR MUST BE AN EMP');
	END IF;
	ELSE
	DBMS_OUTPUT.PUT_LINE('JOB MUST BE ACCOUNTANT OR PROG OR PUB ACCNTANT');
	END IF;
     	END LOOP;

END ADD_EMPLOYEE; 
/

	