DECLARE
	V_E1 NUMBER(5):='&EMP1';
	V_E2 NUMBER(5):='&EMP2';
	CNT1 NUMBER;
	CNT2 NUMBER;
	EMP1 EXCEPTION;
	 EMP2 EXCEPTION;
	EMP12 EXCEPTION;
	

BEGIN
	SELECT COUNT(*) INTO CNT1 FROM EMP WHERE EMPNO=V_E1;
	IF CNT1=0 THEN
	RAISE EMP1;
	ELSIF CNT1=1 THEN
	UPDATE EMP SET SAL=(SAL+(0.1*SAL)) ;
	DBMS_OUTPUT.PUT_LINE('ROWS UPDATED');
	END IF;
	
	SELECT COUNT(*) INTO CNT2  FROM EMP WHERE EMPNO=V_E2;
	IF CNT2=0 THEN 	
	RAISE EMP2;
	ELSIF CNT2=1 THEN
	UPDATE EMP SET SAL=(SAL+(0.2*SAL)) ;
	DBMS_OUTPUT.PUT_LINE('ROWS UPDATED');
	ELSIF (CNT1=0 AND CNT2=0) THEN
	RAISE EMP12;
	END IF;
EXCEPTION
	WHEN EMP1 THEN
	DBMS_OUTPUT.PUT_LINE('EMP1 DOES NOT EXIST');
	WHEN EMP2 THEN
	DBMS_OUTPUT.PUT_LINE('EMP2 DOES NOT EXIST');
	WHEN EMP12 THEN
	DBMS_OUTPUT.PUT_LINE('EMP1 AND EMP2 DOES NOT EXIST');
	
	


END;
/