CREATE OR REPLACE FUNCTION VALID_DEPT_NO
(
   P_DNO DEPT.DEPTNO%TYPE
)
RETURN BOOLEAN
IS
CNT NUMBER;
BEGIN
        SELECT COUNT(*) INTO CNT FROM DEPT WHERE DEPTNO=P_DNO;
         IF(CNT=0) THEN
	DBMS_OUTPUT.PUT_LINE('NO DEPT FOUND');
               RETURN FALSE;
                   END IF;
	IF(CNT=1) THEN
	DBMS_OUTPUT.PUT_LINE('DEPT FOUND');
	END IF;
	RETURN TRUE;


END;
/
------------------------------------
EXECUTION:
CREATE OR REPLACE PROCEDURE SHOW_STRENGTH
(
  P_DEPTNO DEPT.DEPTNO%TYPE
)
IS
	CNT NUMBER;
	
 BEGIN
 IF(VALID_DEPT_NO(20))
 THEN
 DBMS_OUTPUT.PUT_LINE('hi');
 SELECT COUNT(EMPNO) INTO CNT FROM EMP WHERE EMP.DEPTNO=P_DEPTNO;
  DBMS_OUTPUT.PUT_LINE('COUNT OF EMPLOYEES IS:'||' '||CNT);
 END IF;
 
EXCEPTION
		WHEN NO_DATA_FOUND THEN
	      DBMS_OUTPUT.PUT_LINE('DEPT NOT FOUND');
 END SHOW_STRENGTH;
 /