CREATE OR REPLACE PROCEDURE SHOW_RECORDS
(
P_DATE EMP.HIREDATE%TYPE
)
IS
CURSOR C1 IS SELECT * FROM EMP;
 BEGIN
DBMS_OUTPUT.PUT_LINE('EMPNO'||' '||'ENAME'||' '||'SAL'||' '||'DEPTNO'||' '||'HIREDATE');
FOR V_A IN C1
LOOP
IF(P_DATE<V_A.HIREDATE) THEN
DBMS_OUTPUT.PUT_LINE(V_A.EMPNO||' '||V_A.ENAME||' '||V_A.SAL||V_A.DEPTNO||V_A.HIREDATE);
END IF;
END LOOP;
EXCEPTION
	WHEN NO_DATA_FOUND THEN
	DBMS_OUTPUT.PUT_LINE('ERROR!');
END;
/