CREATE OR REPLACE PACKAGE POLYPACK
IS
PROCEDURE POLY1(P_N1 NUMBER,P_N2 OUT NUMBER);
PROCEDURE POLY1(V_X VARCHAR2,V_Y VARCHAR2,V_Z OUT VARCHAR2);

END POLYPACK;


CREATE OR REPLACE PACKAGE BODY POLYPACK
IS
PROCEDURE POLY1(P_N1 NUMBER,P_N2 OUT NUMBER)
IS
BEGIN
P_N2:=P_N1*5;
END POLY1;

PROCEDURE POLY1(V_X VARCHAR2,V_Y VARCHAR2,V_Z OUT VARCHAR2)
IS
BEGIN
V_Z:=CONCAT(V_X,V_Y);

END POLY1;

END POLYPACK;