CREATE OR REPLACE PACKAGE PACK2
IS

PROCEDURE PROC1(P_N NUMBER,P_N1 OUT NUMBER);
FUNCTION FUN1(P_N2 NUMBER) RETURN NUMBER;

END PACK2;
/



CREATE OR REPLACE PACKAGE BODY  PACK2
IS
PROCEDURE TEST
IS
BEGIN
    DBMS_OUTPUT.PUT_LINE('I AM A PRIVATE MEMBER');
END TEST;
PROCEDURE PROC1(P_N NUMBER,P_N1 OUT NUMBER)
IS
BEGIN
TEST;
P_N1:=P_N*5;
DBMS_OUTPUT.PUT_LINE(P_N1);
END PROC1;

FUNCTION FUN1(P_N2 NUMBER) RETURN NUMBER
IS
V_N2 NUMBER;
BEGIN
  V_N2:=P_N2*5;
   RETURN V_N2;
END FUN1;

END PACK2;