CREATE OR REPLACE PROCEDURE ADD_DEPT
(
   P_DNAME IN DEPT.DNAME%TYPE ,
   P_LOCATION IN DEPT.LOC%TYPE )
IS
BEGIN
INSERT INTO DEPT VALUES(D.NEXT_VAL,P_DNAME,P_LOCATION);
        
END ADD_DEPT;
/