CREATE OR REPLACE PROCEDURE ADD_EMPLOYEE
(
  P_JOB EMP.JOB%TYPE,
  M_ID EMP.MGR%TYPE,
  HDATE EMP.HIREDATE%TYPE,
  SALARY EMP.SAL%TYPE,
  COM EMP.COMM%TYPE,
   DEPTID EMP.DEPTNO%TYPE
)
IS
CURSOR C IS SELECT * FROM EMP;
V_C C%ROWTYPE;

BEGIN
        P_JOB:='&JOB';
        M_ID:='&MGR';
        HDATE:='&HIREDATE';
         SALARY:='&SALARY';
         COM:='&COMMSN';
          DEPTID:='DEPTNUMBER';
          FOR V_C IN C
          LOOP
         IF(P_JOB='PROGRAMMER' || P_JOB='ACCOUNTANT'||   P_JOB='PUBLIC ACCOUNTANT')   AND   (M_ID=V_C.EMPNO) AND (HIREDATE>SYSDATE) AND ()
	





       END LOOP;
END;
/