CREATE OR REPLACE FUNCTION USER_ANNUAL_COMP
(
  P_ENO emp.empno%type,
P_SAL emp.sal%type,
P_COMM emp.comm%type
)
RETURN NUMBER
IS
V_EID NUMBER;
V_SAL NUMBER;
V_COMM NUMBER;
V_ANN NUMBER;
BEGIN
   SELECT EMPNO, SAL,NVL(COMM ,0) INTO V_EID,V_SAL,V_COMM FROM EMP WHERE 
   EMPNO=P_ENO;
   V_ANN:=(V_SAL+V_COMM)*12;
   RETURN V_ANN;
	 
END;
/