CREATE OR REPLACE PROCEDURE USER_QUERY_EMP
(
    P_MYENO IN NUMBER,
    p_myjob OUT VARCHAR2,
    p_mysal OUT VARCHAR2
)
IS

V_MYJOB VARCHAR2(20);
V_SAL NUMBER;
BEGIN
SELECT JOB,SAL INTO V_MYJOB,V_SAL FROM EMP WHERE EMPNO=P_MYENO;
DBMS_OUTPUT.PUT_LINE(V_MYJOB|| ' '||V_SAL);


EXCEPTION
	WHEN NO_DATA_FOUND THEN
	DBMS_OUTPUT.PUT_LINE('ERROR!');

END;
/