CREATE OR REPLACE PROCEDURE GET_SAL
(
  V_ENO EMP.EMPNO%TYPE,
   V_SAL OUT NUMBER
)
IS
BEGIN
     SELECT SAL INTO V_SAL FROM EMP WHERE EMPNO=V_ENO;

EXCEPTION
	WHEN NO_DATA_FOUND THEN 
	DBMS_OUTPUT.PUT_LINE(' EMP NOT FOUND ');

END;
/