CREATE OR REPLACE PROCEDURE GET_SAL(P_EMPNO
EMP.EMPNO%TYPE,P_SAL OUT NUMBER)
IS
BEGIN
SELECT SAL INTO P_SAL FROM EMP WHERE EMPNO=P_EMPNO;


EXCEPTION
	WHEN NO_DATA_FOUND THEN
	DBMS_OUTPUT.PUT_LINE('EMPLOYEE NOT FOUND');


END;
/